name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔐 Login no GHCR
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 🧱 Build Backend
      - name: Build backend
        run: docker build -t ghcr.io/${{ github.actor }}/flowizer-backend:latest ./backend

      # 🧱 Build Frontend
      - name: Build frontend
        run: docker build -t ghcr.io/${{ github.actor }}/flowizer-frontend:latest ./frontend

      # 🚀 Push Backend
      - name: Push backend
        run: docker push ghcr.io/${{ github.actor }}/flowizer-backend:latest

      # 🚀 Push Frontend
      - name: Push frontend
        run: docker push ghcr.io/${{ github.actor }}/flowizer-frontend:latest

      # 🔥 Deploy na VPS
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker service update --force flowizer_backend
            docker service update --force flowizer_frontend
